name: Build and deploy ASP.Net Core app to Azure Web App - Natuliga

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          cd API
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd API
          dotnet publish -c Release -o ./publish

      - name: List publish directory contents
        run: |
          ls -la ./API/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./API/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D888DBA7E89545A897991FFCEC519593 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3856E15CA81249389C2BB74DA9913D00 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5A201EC13AF45728D149AEA34683E79 }}

      - name: Retrieve Connection String from Azure
        id: get-connection-string
        run: |
          echo "CONNECTION_STRING=$(az webapp config connection-string show --name Natuliga --resource-group Natuliga_Group --query "ConnectionStrings__DefaultConnection" -o tsv)" >> $GITHUB_ENV

      - name: Print current directory
        run: pwd

      - name: List contents of current directory
        run: ls -la

      - name: Run EF Database Update
        run: |
          cd API
          dotnet ef database update --context natuliga-database --connection "$CONNECTION_STRING" --project API.csproj

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Natuliga'
          slot-name: 'Production'
          package: ./publish

